### ISSUE TITLE
Running without Snap?

### ISSUE THREAD

**Issue by hook-s3c** [fredldotme/qShodan#1]
Just wondering if it's possible... nothing in the Readme

**Comment by fredldotme** [comment]
You could, it's based on Qt and builds using qmake. I'd still recommend the snap builds for daily use.

**Comment by fredldotme** [comment]
What platform would you like to run this on?

**Comment by hook-s3c** [comment]
ubuntu 18.04, x86_64

**Comment by hook-s3c** [comment]
some basic documentation on how to build and deps would be greatly appreciated - I can test

**Comment by fredldotme** [comment]
If you want to build with Qt upstream you just need Qt upstream,
if you want to build with Qt provided by Ubuntu you could study the snapcraft.yaml, it's all in there.
Documentation on how to build might follow in the future.
