### ISSUE TITLE
Problem to enter api key

### ISSUE THREAD

**Issue by vokaliz** [fredldotme/qShodan#2]
Hello! I am installed qshodan on my UBports Meizu and I cant enter the API key. Application allways shows me keybord and I cant paste or manually entering Shodan api key. Keybord blocking me api window. After reinstall app problem steel have. Fix the problem, please?

**Comment by fredldotme** [comment]
Positioning the items (camera output, labels, buttons) has problems currently so I'd suggest going the route of using the camera to scan the API key for now. I'll see if I can improve this.

**Comment by fredldotme** [comment]
Fixed by 7633f56c9dafbf12f17d52d84b00ebf589a92749
